### ISSUE TITLE
[bigquery] notifier crashes with panic nil dereference

### ISSUE THREAD

**Issue by devjgm** [GoogleCloudPlatform/cloud-build-notifiers#110]
I'm using the BigQuery notifier, and it works sometimes but seems to crash often w/ the following stack trace:

```
2021/05/21 19:16:54 http: panic serving 169.254.8.129:39528: runtime error: invalid memory address or nil pointer dereference
goroutine 49 [running]:
net/http.(*conn).serve.func1(0xc0003c0e60)
	/usr/local/go/src/net/http/server.go:1824 +0x153
panic(0xd78aa0, 0x1592d30)
	/usr/local/go/src/runtime/panic.go:971 +0x499
main.(*bqNotifier).SendNotification(0xc0003d2d50, 0xff2320, 0xc0001cc240, 0xc000231500, 0x2928, 0x3000)
	/go-src/bigquery/main.go:238 +0x846
github.com/GoogleCloudPlatform/cloud-build-notifiers/lib/notifiers.newReceiver.func1(0xff09c0, 0xc000337260, 0xc000460200)
	/go-src/lib/notifiers/notifiers.go:448 +0x938
net/http.HandlerFunc.ServeHTTP(0xc0005e0ea0, 0xff09c0, 0xc000337260, 0xc000460200)
	/usr/local/go/src/net/http/server.go:2069 +0x44
net/http.(*ServeMux).ServeHTTP(0x15af920, 0xff09c0, 0xc000337260, 0xc000460200)
	/usr/local/go/src/net/http/server.go:2448 +0x1ad
net/http.serverHandler.ServeHTTP(0xc000337180, 0xff09c0, 0xc000337260, 0xc000460200)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc0003c0e60, 0xff23c8, 0xc0001cc180)
	/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x39b 
```

The config file I'm using is:

```yaml
apiVersion: cloud-build-notifiers/v1
kind: BigQueryNotifier
metadata:
  name: google-cloud-cpp-bigquery-notifier
spec:
  notification:
    filter: build.substitutions["REPO_NAME"] == "google-cloud-cpp"
    delivery:
      table: projects/936212892354/datasets/cloudbuild/tables/google_cloud_cpp
```

My project is tracking this bug at https://github.com/googleapis/google-cloud-cpp/issues/6580.
