### ISSUE TITLE
Unable to configure cloud build slack notifier

### ISSUE THREAD

**Issue by rajneeshmith** [GoogleCloudPlatform/cloud-build-notifiers#143]
```
gcloud run deploy slack-ci-cd-notification \
>    --image=us-east1-docker.pkg.dev/gcb-release/cloud-build-notifiers/slack:latest \
>    --no-allow-unauthenticated \
>    --update-env-vars=CONFIG_PATH=gs://tutubi-project/slack-notifier.yaml,PROJECT_ID=tutubi-75285
Deploying container to Cloud Run service [slack-ci-cd-notification] in project [tutubi-75285] region [europe-west3]
⠛ Deploying... Cloud Run error: The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable. Logs for this revision might contain more information.
  ⠏ Creating Revision...
Logs URL: https://console.cloud.google.com/logs/viewer?pro
ject=tutubi-75285&resource=cloud_run_revision/service_name/slack-ci-cd-notification/revision_name/slack-ci-cd-notification-00004-sip&advancedFilter=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22slack-ci-cd-notification%22%0Aresource.label
s.revision_name%3D%22slack-ci-cd-notification-00004-sip%22
For more troubleshooting guidance, see https://cloud.google.com/run/docs/troubleshooting#container-failed-to-start
X Deploying... Cloud Run error: The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable. Logs for this revision might contain more information.

Logs URL: https://console.cloud.google.com/logs/viewer?pro
ject=tutubi-75285&resource=cloud_run_revision/service_name/slack-ci-cd-notification/revision_name/slack-ci-cd-notification-00004-sip&advancedFilter=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22slack-ci-cd-notification%22%0Aresource.label
s.revision_name%3D%22slack-ci-cd-notification-00004-sip%22
For more troubleshooting guidance, see https://cloud.google.com/run/docs/troubleshooting#container-failed-to-start
  . Routing traffic...
  ✓ Setting IAM Policy...



Deployment failed
ERROR: (gcloud.run.deploy) Cloud Run error: The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable. Logs for this revision might contain more information.
```

I am following this doc https://cloud.google.com/build/docs/configuring-notifications/configure-slack
Stuck on Step-9  (Deploy your notifier to Cloud Run)

**Comment by rajneeshmith** [comment]
Figured it out. `spec.notification.filter` is required 

```
apiVersion: cloud-build-notifiers/v1
kind: SlackNotifier
metadata:
  name: ci-cd-slack-notifier
spec:
  notification:
    filter: build.status == Build.Status.SUCCESS
    delivery:
      webhookUrl:
        secretRef: webhook-url
  secrets:
  - name: webhook-url
    value: projects/project-id/secrets/secret-name/versions/latest
    ```
