### ISSUE TITLE
[HTTP Notifications] Empty Body

### ISSUE THREAD

**Issue by mikeyShopeeRiver** [GoogleCloudPlatform/cloud-build-notifiers#150]
Hi! I've setup a flask http server and followed the instructions [here](https://cloud.google.com/build/docs/configuring-notifications/configure-http) to be able to receive notifications on our CI/ID in cloud build. Here is my configuration file:
```
apiVersion: cloud-build-notifiers/v1
kind: HTTPNotifier
metadata:
  name: example-http-notifier
spec:
  notification:
    filter: build.status in [Build.Status.SUCCESS, Build.Status.FAILURE, Build.Status.TIMEOUT, Build.Status.WORKING]
    delivery:
      # The `http(s)://` protocol prefix is required.
      url: https://ef02-152-32-107-144.ngrok.io/gcp/payload
```
I'm currently using ngrok to test locally and the filters are working and are receiving the requests send by the HTTP Notifier. However, instead of receiving a json payload, I get an empty body. Here are values of the header and body received:
```
Host: ef02-152-32-107-144.ngrok.io
User-Agent: GCB-Notifier/0.1 (http)
Content-Length: 0
Accept-Encoding: gzip
Content-Type: application/json
X-Forwarded-For: 2600:1900:2000:da::5
X-Forwarded-Proto: https
```

Body: '' (just an empty string)

Any reason for the empty body instead of the json payload?

Thank you!
